# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Project
group=de.cech12.brickfurnace
mod_version=4.4.1.0
mod_id=brickfurnace
mod_name=Brick Furnace
mod_author=Cech12
mod_license=The MIT License (MIT)
mod_url=https://github.com/cech12/BrickFurnace
mod_issue_tracker=https://github.com/cech12/BrickFurnace/issues
description=A mod which adds Brick Furnaces.

# Common
java_version=21
minecraft_version=1.21.4
minecraft_version_range=[1.21.4, 1.21.5)

# Fabric
fabric_version=0.116.0+1.21.4
fabric_loader_version=0.16.10
cloth_config_version=17.0.144
mod_menu_version=13.0.1

# Forge
forge_version=54.0.26
forge_version_range=[54.0.26,)
forge_loader_version_range=[0,)

# NeoForge
neoforge_version=21.4.121
neoforge_version_range=[21.4.121,)
neoforge_loader_version_range=[2,)

# jei
jei_version=20.0.0.4
jei_version_range=[20.0.0.4,)

# rei
rei_version=18.0.804
rei_version_range=[18.0.804,)
architectury_version=15.0.3

#the one probe
top_version=1.21_neo-12.0.3-5
top_version_range=[1.21_neo-12.0.3,)

# immersive engineering
immersive_engineering_version=1.21.1-12.0.0-182.77
immersive_engineering_version_range=[1.21.1-12.0.0,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false