# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Project
group=de.cech12.brickfurnace
mod_version=4.3.1.0
mod_id=brickfurnace
mod_name=Brick Furnace
mod_author=Cech12
mod_license=The MIT License (MIT)
mod_url=https://github.com/cech12/BrickFurnace
mod_issue_tracker=https://github.com/cech12/BrickFurnace/issues
description=A mod which adds Brick Furnaces.

# Common
java_version=21
minecraft_version=1.21.3
minecraft_version_range=[1.21.3, 1.22)

# Fabric
fabric_version=0.107.0+1.21.3
fabric_loader_version=0.16.9
cloth_config_version=16.0.141
mod_menu_version=12.0.0

# Forge
forge_version=53.0.45
forge_version_range=[53.0.45,)
forge_loader_version_range=[50,)

# NeoForge
neoforge_version=21.3.56
neoforge_version_range=[21.3.56,)
neoforge_loader_version_range=[2,)

# jei
jei_version=19.19.0.219
jei_version_range=[19.19.0.219,)

# rei
rei_version=17.0.789
rei_version_range=[17.0.789,)
architectury_version=14.0.4

#the one probe
top_version=1.21_neo-12.0.3-5
top_version_range=[1.21_neo-12.0.3,)

# immersive engineering
immersive_engineering_version=1.21.1-12.0.0-182.77
immersive_engineering_version_range=[1.21.1-12.0.0,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false